# site settings
title: Zach Kelleher
email: zkelleher12@gmail.com
description: UX Designer and Developer who is focused on building functional brands and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
# url: https://zkelleher.github.io
author: Zach Kelleher

# Project Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# homepage tiles
tiles-source: project # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/zkelleher
instagram_url: https://www.instagram.com/zeven_odd/
linkedin_url: https://www.linkedin.com/in/zach-kelleher-603/
codepen_url: https://codepen.io/zkelleher12
dribbble_url: https://dribbble.com/zkelleher

livereload: true

# build settings
markdown: kramdown

sass:
  style: compressed
